# -*- coding: utf-8 -*-
"""jogo_com_numeros_aleatorios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16W3qdTGi9Aso0E4M6nwafDedgdXnQaQ7

# Lógica de Programação com Python

Usando parâmetros na Função
"""

from random import randrange

def saud_com_param (nome_call):
  print(f"Prazer em te conhecer, {nome_call}")

def game():
  print("Que bom que resolveu se juntar a mim!")
  num=int(input("Agora, escolha um número de 1 até 10 "))
  minha_escolha = randrange(1,11)
  if num==minha_escolha:
    print("Parabéns, você acertou")
  else: 
    print("Que pena, você errou. O meu número era ", minha_escolha, )


nome = input("Olá! Qual o seu nome? ")

saud_com_param(nome)

print("Agora vamos fazer um jogo bem divertido. Espero que goste \nEle se chama Jogo da advinhação.\n Pensarei em um número aleatório e você deve tentar acertá-lo")
aceite =input("Aceita jogar? Caso sim, digite S, caso não, digite N.")

if aceite == "S":
  jogar = True
  while jogar == True:
    game()
    continua = input("Deseja continuar jogando? (Se sim, digite S, se não, digite N)")
    continuas= True
    if continua == "S":
      jogar = True
      continuas = False
    elif continua == "N":
      jogar = False
      continuas = False

    while continuas == True:
      if continua == "S":
        jogar = True
        continuas = False
      elif continua == "N":
        jogar = False
        continuas = False
      else:
        print("Digite um valor válido")
  print("Muito obrigada por jogar comigo. Te aguardo para um novo jogo em breve")
else:
  print("Que pena que decidiu não jogar. Espero que nos vejamos novamente em breve. Até mais :) ")